### PR TITLE
allow setting of ssl_verification without ssl_key...

### PR DESCRIPTION
**Pull request by ctippler**
Problem:
- the ssl_verification is not considered if we don't define ssl_key/ssl_cert
- fix docs because the ssl_verification is by default "true"

### CODE REVIEW

**Comment by aryaantony92** [comment]
@ctippler May I know the reason for this change, i.e considering ssl_verification even if ssl_key and ssl_cert is not defined.

**Comment by ctippler** [comment]
Hi sure,

the reason is that by default elasticsearch runs in https mode but the used certificate ist not a public/autorized certificate (so the ssl_verification will fail).

So in our configuration we don't have a ssl_key/ssl_cert defined, but we want to run it in https mode.  
```
pimcore_elasticsearch_client:
    es_clients:
        default:
            hosts: ['https://localhost:9200']
            username: 'elastic'
            password: '%env(ELASTICSEARCH_PASSWORD)%'
            logger_channel: 'pimcore.elasicsearch'
            ssl_verification: false
```

Without the changes in this PR the  ssl_verification: false is never set, so the connection won't work.

Regards,
Christian

**Comment by fashxp** [comment]
@ctippler I see, but the quote 

> fix docs because now the ssl_verification is by default "true"

is not correct, right? It was already `true` by default, wasn't it? 
So there should not be any change in default behavior.

**Comment by ctippler** [comment]
Hi @fashxp ,
I changed "fix docs because now the ssl_verification is by default "true"" to "fix docs because the ssl_verification is by default "true". I just assumed that it has been "false" earlier days, but i don't know :-). At least now its true. So if you set up elasticsearch with a valid certificated it will run without problems (no change in the default behavior needed).

Regards,
Christian

**Review by fashxp — APPROVED** [review]

**Comment by fashxp** [comment]
thx for clarification

**Comment by aryaantony92** [comment]
@ctippler Thank you!

**Pull request merged**
